### ISSUE TITLE
测试不成功

### ISSUE THREAD

**Issue by liangdaozheng** [SuperMap/iClient3D-vue#13]
![image](https://user-images.githubusercontent.com/48799183/173237391-733d9219-4866-4ff9-bfe4-811b1c59208f.png)
![image](https://user-images.githubusercontent.com/48799183/173237421-ab4d88ec-7476-4c31-b532-cb828b17287a.png)
![image](https://user-images.githubusercontent.com/48799183/173237435-eda8138b-c160-406f-b230-9736aa3f5bd1.png)
![image](https://user-images.githubusercontent.com/48799183/173237457-3e9be8e9-02f2-4beb-b784-0e4f123e40d8.png)
![image](https://user-images.githubusercontent.com/48799183/173237483-fed056f2-b8b7-44f2-b70a-dfaf91e45596.png)
给个意见呗？

**Comment by houluy** [comment]
应该是版本问题，不能用vue最新版。我退回了vue@3.0.5可以了。

**Comment by liangdaozheng** [comment]
![image](https://user-images.githubusercontent.com/48799183/173269505-d6eca66e-48b2-4aa8-a34c-ad385c81fa12.png)
